INSERT INTO ALO_USUARIO (ID, NOME, LOGIN, SENHA, EMAIL) 
VALUES (1, 'Andre', 'andre', '12345', 'andre@gmail.com');

ALTER SEQUENCE ALO_USUARIO_ID_SEQ RESTART WITH 2;

INSERT INTO ALO_PERFIL (ID, DESCRICAO) VALUES (1, 'Administrador');
INSERT INTO ALO_PERFIL (ID, DESCRICAO) VALUES (2, 'Gerente');
INSERT INTO ALO_PERFIL (ID, DESCRICAO) VALUES (3, 'Cliente');

ALTER SEQUENCE ALO_USUARIO_ID_SEQ RESTART WITH 4;

INSERT INTO ALO_RECURSO (ID, NOME, CHAVE) VALUES (1, 'Tela Usuário', 'usuario');
INSERT INTO ALO_RECURSO (ID, NOME, CHAVE) VALUES (2, 'Tela Perfil', 'perfil');
INSERT INTO ALO_RECURSO (ID, NOME, CHAVE) VALUES (3, 'Tela Recurso', 'recurso');

ALTER SEQUENCE ALO_RECURSO_SEQ RESTART WITH 4;
